# Generated by Django 4.0.4 on 2023-06-05 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cafe_id', models.CharField(max_length=100)),
                ('user_id', models.CharField(max_length=100)),
            ],
        ),
    ]
