# Generated by Django 4.0.4 on 2023-06-09 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafe_api', '0002_favorite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cafe',
            old_name='name',
            new_name='data',
        ),
        migrations.RemoveField(
            model_name='cafe',
            name='user',
        ),
    ]
