# Generated by Django 4.0.4 on 2023-06-09 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe_api', '0003_rename_name_cafe_data_remove_cafe_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafe',
            name='data',
            field=models.JSONField(),
        ),
    ]
