# Generated by Django 4.0.4 on 2023-06-09 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafe_api', '0004_alter_cafe_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
